import { App } from 'vue'
import {
  ElButton,
  ElCheckbox,
  ElContainer,
  ElForm,
  ElInput,
  ElLink,
  ElMenu,
  ElRadio,
  ElTabs,
  ElDropdown,
  ElAvatar,
  ElCol,
  ElRow,
  ElSelect,
  ElDatePicker,
  ElBreadcrumb,
  ElTable,
  ElPagination,
  ElImage,
  ElDialog,
  ElTree,
  ElCard,
  ElTooltip,
  ElMessage
} from 'element-plus'
// affix.ElAffix,
// alert.ElAlert,
// autocomplete.ElAutocomplete,
// avatar.ElAvatar,
// backtop.ElBacktop,
// badge.ElBadge,
// breadcrumb.ElBreadcrumb,
// button.ElButton,
// calendar.ElCalendar,
// card.ElCard,
// carousel.ElCarousel,
// cascader.ElCascader,
// cascaderPanel.ElCascaderPanel,
// checkTag.ElCheckTag,
// checkbox.ElCheckbox,
// col.ElCol,
// collapse.ElCollapse,
// collapseTransition.ElCollapseTransition,
// colorPicker.ElColorPicker,
// configProvider.ElConfigProvider,
// container.ElContainer,
// datePicker.ElDatePicker,
// descriptions.ElDescriptions,
// dialog.ElDialog,
// divider.ElDivider,
// drawer.ElDrawer,
// dropdown.ElDropdown,
// empty.ElEmpty,
// form.ElForm,
// icon.ElIcon,
// image.ElImage,
// imageViewer.ElImageViewer,
// input.ElInput,
// inputNumber.ElInputNumber,
// link.ElLink,
// menu.ElMenu,
// pageHeader.ElPageHeader,
// pagination.ElPagination,
// popconfirm.ElPopconfirm,
// popover.ElPopover,
// popper.ElPopper,
// progress.ElProgress,
// radio.ElRadio,
// rate.ElRate,
// result.ElResult,
// row.ElRow,
// scrollbar.ElScrollbar,
// select.ElSelect,
// selectV2.ElSelectV2,
// skeleton.ElSkeleton,
// slider.ElSlider,
// space.ElSpace,
// steps.ElSteps,
// _switch.ElSwitch,
// table.ElTable,
// tabs.ElTabs,
// tag.ElTag,
// timePicker.ElTimePicker,
// timeSelect.ElTimeSelect,
// timeline.ElTimeline,
// tooltip.ElTooltip,
// transfer.ElTransfer,
// tree.ElTree,
// upload.ElUpload
const components = [
  ElButton,
  ElForm,
  ElInput,
  ElRadio,
  ElTabs,
  ElCheckbox,
  ElLink,
  ElContainer,
  ElMenu,
  ElDropdown,
  ElAvatar,
  ElCol,
  ElRow,
  ElSelect,
  ElDatePicker,
  ElBreadcrumb,
  ElTable,
  ElPagination,
  ElImage,
  ElDialog,
  ElTree,
  ElCard,
  ElTooltip,
  ElMessage
]

export default function (app: App): void {
  for (const component of components) {
    //app.component(component.name, component)
    app.use(component)
  }
}
